use_frameworks!

platform :ios, '15.0'

target 'AppRouter-iOS_Example' do
  pod 'AppRouter-iOS', :path => '../'
  
  pod 'SnapKit'

  target 'AppRouter-iOS_Tests' do
    inherit! :search_paths
  end
end
